version: 0.6 b{build}
image: Visual Studio 2017
configuration: Release
platform:
  - x86
  # - x64
# clone_depth: 1
clone_folder: c:\projects\CommandTrayHost
install:
- cmd: >-
    vcpkg install rapidjson rapidjson:x64-windows nlohmann-json nlohmann-json:x64-windows
# before_build:
#   - cmd: cd c:\projects\CommandTrayHost
#   - cmd: dir /a CommandTrayHost
build:
  project: c:\projects\CommandTrayHost\CommandTrayHost.sln
  verbosity: minimal
after_build:
- cmd: msbuild "c:\projects\CommandTrayHost\CommandTrayHost.sln" /verbosity:minimal /p:Configuration=Release /p:Platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- cmd: >-
    cd c:\projects\CommandTrayHost

    mkdir CommandTrayHost-x64

    mkdir CommandTrayHost-x86

    copy x64\Release\CommandTrayHost.exe CommandTrayHost-x64\

    copy Release\CommandTrayHost.exe CommandTrayHost-x86\

    curl -L -o upx.zip https://github.com/upx/upx/releases/download/v3.94/upx394w.zip

    7z e upx.zip *.exe -r

    upx CommandTrayHost-x64\CommandTrayHost.exe

    upx CommandTrayHost-x86\CommandTrayHost.exe

    7z a -tzip CommandTrayHost.zip .\CommandTrayHost-x64\ .\CommandTrayHost-x86\
artifacts:
- path: CommandTrayHost.zip
  name: CommandTrayHost

deploy:
  release: $(appveyor_build_version)
  description: 'nightly'
  provider: GitHub
  auth_token:
    secure: 6BqGKqbQbDfnZ3Y7SHvdQkPVCjXcJ1GIgPe41oD8K7ttPY/ivWN3iMyq2eZ1s4RD # your encrypted token from GitHub
  artifact: CommandTrayHost            # upload all NuGet packages to release assets
  prerelease: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only

cache: c:\tools\vcpkg\installed\
